.TH "/home/krishna/Documents/csn361/3/1.c" 3 "Thu Aug 22 2019" "3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/krishna/Documents/csn361/3/1.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBfindClass\fP (char str[])"
.br
.ti -1c
.RI "void \fBseparate\fP (char str[], char ipClass)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char findClass (char str[])"
This method will be used to find Class\&. 
.PP
\fBAuthor\fP
.RS 4
Krishna Yeswanth 
.RE
.PP
\fBParameters\fP
.RS 4
\fIchar[]\fP used to get Class 
.RE
.PP
\fBDate\fP
.RS 4
8/22/2019 
.RE
.PP

.SS "int main (int argc, char * argv[])"

.SS "void separate (char str[], char ipClass)"
This method will be used to chat\&. 
.PP
\fBAuthor\fP
.RS 4
Krishna Yeswanth 
.RE
.PP
\fBParameters\fP
.RS 4
\fIchar[]\fP and ipClass for Network ID 
.RE
.PP
\fBDate\fP
.RS 4
8/22/2019 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 3 from the source code\&.
