.TH "/home/krishna/Documents/csn361/3/2_cli.c" 3 "Thu Aug 22 2019" "3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/krishna/Documents/csn361/3/2_cli.c
.SH SYNOPSIS
.br
.PP
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBflag\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBclearBuf\fP (char *b)"
.br
.ti -1c
.RI "int \fBrecvFile\fP (char *buf, int s)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define flag   0"

.SH "Function Documentation"
.PP 
.SS "void clearBuf (char * b)"
This method will be used to empty char*\&. 
.PP
\fBAuthor\fP
.RS 4
Krishna Yeswanth 
.RE
.PP
\fBParameters\fP
.RS 4
\fIchar\fP pointer(char*) 
.RE
.PP
\fBDate\fP
.RS 4
8/22/2019 
.RE
.PP

.SS "int main (int argc, char * argv[])"

.SS "int recvFile (char * buf, int s)"
This method will be used to print file\&. 
.PP
\fBAuthor\fP
.RS 4
Krishna Yeswanth 
.RE
.PP
\fBParameters\fP
.RS 4
\fIchar*\fP buf and int size 
.RE
.PP
\fBDate\fP
.RS 4
8/22/2019 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 3 from the source code\&.
